#!/usr/bin/bash
xhost +SI:localuser:$USER
xss-lock -- slock &

exec picom &
exec nitrogen --restore &

setxkbmap -layout 'fr' -variant -model 'pc105' 'us-azerty' -option 'ctrl:swapcaps' 

exec dbus-launch --exit-with-session emacs --debug-init
