#!/usr/bin/bash

exec picom &
exec nitrogen --restore &

xss-lock -- slock &

setxkbmap -layout 'fr' -variant 'us-azerty' -option 'ctrl:swapcaps' 

emacs --daemon --debug-init -f exwm-enable
exec dbus-launch --exit-with-session  emacsclient -c 
